Project2: TreeNode.o B_Tree.o main.o
	g++ -g TreeNode.o B_Tree.o main.o -o Project2
TreeNode.o: TreeNode.cpp TreeNode.h
	g++ -c -g TreeNode.cpp
B_Tree.o: B_Tree.cpp B_Tree.h
	g++ -c -g B_Tree.cpp
main.o: main.cpp
	g++ -c -g main.cpp
run: Project2
	./Project2
